### ISSUE TITLE
errors about malformed jwt token

### ISSUE THREAD

**Issue by Puyodead1** [yuchiu/Netflix-Clone#2]
getting errors about malformed JWT Token

**Comment by yuchiu** [comment]
Thank you for letting me know.

The issue was caused by including empty bearer token in authorization header for HTTP request when user are not signed in(no JWT in localstore).

I fixed in [#118 commit fbc87556da660606a7910166b85904212be6bb6f](https://github.com/yuchiu/Netflix-Clone/commit/fbc87556da660606a7910166b85904212be6bb6f) by not including bearer token when JWT is not in localstore.
